language: node_js
node_js:
- node
- '6'
- '4'
script: npm run test-ci
deploy:
  provider: npm
  email: christopher.andrejewski@gmail.com
  api_key:
    secure: xRkr35aA2LBXJK21ku24ut9FDKBa/xUafEu0SOi/xZfGojkqsO2K42oyhbbeT5hKw1yaEouH+/J3Syr9n9fO9P37SD6AZPnddkWs600owfOck5dp5VGWCm/dK4pwbfX7UKgLbTbBUpkQzVDmdvQSUlARJ/IadDwbHuSJtPpXlhFoRn3TtkKvdYCX2i8FovPa5PIO9o5V0fTQO3d/heNLPLSp+JYpzfGO5ZASk7012IjNLBpxNTTgyHtbiVInrBb0jgrjoSpqahZ4xOYfX7QzSfHAuzT68ec1wfo5cY6BBTDOLwA5YHx0PxNUkL/90UevEq6CeQjUS5vkLBCRS3zleB7haSTR5f9zME4GKEuvQL1hrFAIlP/oXMJyKYlrbE7VQ25nic1emRACfbxv/441v5HTQ5A2H6zI4OdraHzak6WpiQQuo2BVZmPmVIai4YLLFwN1qxWLPqZE0IMFXcpEkqQ/WRgZnkymjNf7zCWw+1gGAnydlZ3J8wYOYMSlqH8b31DZlIUneUg3aLL6sems9CLnsH4Xf+dCiEGqFxc9hTbQXEW3z2hkXKkzPlYX45FgSH80wruM6E6DjAW/84DB+XslN8rpFMRjKnAksQWxCNbgYs1nwMxJoUZtGAH9EdnI64DQI0g+qQwBhrqXWdAqOqOYVuiCYBbLJAg7cdWLWFA=
  on:
    tags: true
    repo: andrejewski/rove
after_success:
- npm run coveralls
